name: python-backend-workflows

on:
  pull_request:
    types:
      - opened
      - closed
      - synchronize

jobs:
  #   lint-test: to be determined

  markdown-check:
    uses: ai-cfia/github-workflows/.github/workflows/workflow-markdown-check.yml@main
    with:
      config-file-path: ".mlc_config.json"
    secrets: inherit

  repo-standard:
    uses: ai-cfia/github-workflows/.github/workflows/workflow-repo-standards-validation.yml@main
    secrets: inherit
